<?php

/**
 * @file
 * Main latex_generate file.
 */

/**
 * Implements hook_perm().
 */
function latex_generate_perm() {
  return array('latex generate');
}

/**
 * Implements hook_menu().
 */
function latex_generate_menu() {
  $items = array();

  $items['latex-generate'] = array(
    'title' => 'Generate template',
    'description' => 'Data input.',
    'access callback' => 'user_access',
    'access arguments' => array('latex generate'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('latex_generate_input_form'),
    'type' => MENU_CALLBACK,
    'file' => 'latex_generate.input.inc',
    'file path' => drupal_get_path('module', 'latex_generate') . '/includes',
  );

  return $items;
}
